### ISSUE TITLE
Проблема с SERVERLINK

### ISSUE THREAD

**Issue by stdex** [Alex300/Online-Consultant#2]
Переменная SERVERLINK формируется:
https://github.com/Alex300/Online-Consultant/blob/master/oconsultant/models/OcThread.php#L408
https://github.com/Alex300/Online-Consultant/blob/master/oconsultant/models/OcThread.php#L502

На выходе:
index.php?e=oconsultant&amp;m=chat

Вследствие чего AJAX запрос на URL index.php?e=oconsultant&amp;m=chat&a=ajxRefresh неправильно обрабатывается - выдает "Не найдено (404)".

Правильным вариантом является использование:
cot_url('oconsultant', array('m' => 'chat'), '', true)

**Comment by Alex300** [comment]
Почему же правильным?
Отключите URL Editor и попробуйте

```
var_dump(cot_url('oconsultant', array('m' => 'chat'), '', true));
```

Вы удивитесь, но на выходе будет:

```
index.php?e=oconsultant&amp;m=chat
```
